/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MiniTradingApp;

import java.io.IOException;

import yahoofinance.Stock;
import yahoofinance.YahooFinance;
import org.apache.log4j.BasicConfigurator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
    	BasicConfigurator.configure();
    	Stock stock = YahooFinance.get("INTC");
    	System.out.println(new App().getGreeting());
    	stock.print();
    	
    }
}
